### ISSUE TITLE
Readme says wadb rather than wandb

### ISSUE THREAD

**Issue by scottire** [levtelyatnikov/pytorch-lightning-wadb-code-backbone#1]
Thanks a lot for sharing this in the PyTorch Lightning forum! 👏

I've noticed it's says wadb rather than wandb in the readme. It would be nice to fix that to say wandb so it's correct. I'd be happy to open a PR and fix it if you don't get around to it before next week. 

Regardless, I mainly wanted to open this issue to show appreciation for creating this repo 🙂

**Comment by levtelyatnikov** [comment]
Solved, thank you!!
